competition_name: Titanic
target: Survived
id_column: PassengerId
task_type: binary  # or regression|multiclass
metric_name: auc   # Kaggle scores accuracy; we track AUC locally
cv:
  scheme: stratified   # kfold|stratified|group|timeseries
  n_splits: 5
  shuffle: true
  random_state: 42
  group_column: null
  time_column: null
paths:
  train_csv: data/train.csv
  test_csv: data/test.csv
kaggle:
  competition: titanic
