features:
  scale_numeric: true
  encode_categorical: true
  impute_numeric: median
  impute_categorical: most_frequent
  add_family: true
  add_is_alone: true
  add_title: true
  add_deck: false
  add_ticket_group_size: false
  log_fare: true
  bin_age: false
  rare_title_threshold: 10
