models:
  - name: rf
    params: {n_estimators: 400, max_depth: 6, random_state: 42, n_jobs: -1}
  - name: logistic
    params: {C: 1.0, random_state: 42}
  - name: ridge
    params: {alpha: 1.0, random_state: 42}
