models:
  - name: xgb
    params: {n_estimators: 500, max_depth: 4, learning_rate: 0.05, subsample: 0.9, colsample_bytree: 0.9, reg_lambda: 1.0, random_state: 42}
  - name: catboost
    params: {iterations: 800, depth: 4, learning_rate: 0.05, l2_leaf_reg: 3.0, random_seed: 42, verbose: false}
  - name: hgb
    params: {learning_rate: 0.06, max_depth: 3, random_state: 42}
  - name: gbc
    params: {n_estimators: 300, learning_rate: 0.05, max_depth: 3, random_state: 42}
  - name: logistic
    params: {C: 1.0, random_state: 42}
  - name: extra_trees
    params: {n_estimators: 500, max_depth: null, random_state: 42}
  - name: ridge
    params: {alpha: 1.0}
  - name: sgd_logistic
    params: {loss: log_loss, max_iter: 3000, tol: 1e-3, random_state: 42}
  - name: knn
    params: {n_neighbors: 21, weights: distance}
